name: hello-world
on: 
  push:
    branches:
       - prod
  pull_request:
    branches:
       - dev
jobs:
  push-job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
  
  pull-job:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World Pull Request!"
